#!/bin/bash -e

# Copyright 2016 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/base/rc/config

if [ -f ${CURRENT_DIR}/Gemfile ]; then
    RUBY_VERSION=$(/usr/bin/ruby /var/lib/tsuru/ruby/ruby_version_eval.rb ${CURRENT_DIR}/Gemfile 2>/dev/null || echo "")
fi

if [ -f ${CURRENT_DIR}/.ruby-version -a "${RUBY_VERSION}" == "" ]; then
    RUBY_VERSION=$(cat ${CURRENT_DIR}/.ruby-version)
fi

RUBY_VERSION=${RUBY_VERSION:-2.2.3}

echo "-- Using ruby version: $RUBY_VERSION --"

# Install Ruby
mkdir -p "/home/application/ruby/ruby-$RUBY_VERSION"
curl -s --retry 3 -L "https://heroku-buildpack-ruby.s3.amazonaws.com/cedar-14/ruby-$RUBY_VERSION.tgz" | tar xz -C "/home/application/ruby/ruby-$RUBY_VERSION"

sudo cp /home/application/ruby/ruby-$RUBY_VERSION/bin/* /usr/bin

# Install Bundler
gem install bundler


if [ -f ${CURRENT_DIR}/Gemfile ]; then
    pushd $CURRENT_DIR && bundle install --deployment --without ${BUNDLE_WITHOUT-development:test}
    popd
fi
