#!/bin/bash -e

# Copyright 2016 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/base/rc/config

if [ -f ${CURRENT_DIR}/Gemfile ]; then
    RUBY_VERSION=$(/usr/bin/ruby /var/lib/tsuru/ruby/ruby_version_eval.rb ${CURRENT_DIR}/Gemfile 2>/dev/null || echo "")
fi

if [ -f ${CURRENT_DIR}/.ruby-version -a "${RUBY_VERSION}" == "" ]; then
    RUBY_VERSION=$(cat ${CURRENT_DIR}/.ruby-version)
fi

RUBY_VERSION=${RUBY_VERSION:-2.2.3}

echo "-- Using ruby version: $RUBY_VERSION --"

RUBY_REPO=${RUBY_REPO:-https://heroku-buildpack-ruby.s3.amazonaws.com/cedar-14}

RUBY_TARGET="$RUBY_REPO/ruby-$RUBY_VERSION.tgz"

echo "-- Fetching ruby from: $RUBY_TARGET --"

# Install Ruby
mkdir -p "/home/application/ruby"
curl -s --retry 3 -L "$RUBY_TARGET" | tar xz -C "/home/application/ruby"

if [ -z "$GEM_SOURCE" ]; then
    gem install bundler
else
    echo "-- Using $GEM_SOURCE as remote gem source --"
    gem install bundler --source=$GEM_SOURCE
fi

if [ -f ${CURRENT_DIR}/Gemfile ]; then
    if [ ! -z "$GEM_SOURCE" ]; then
        sed -i "s,https\?://rubygems.org/\?,$GEM_SOURCE," ${CURRENT_DIR}/Gemfile
    fi
    pushd $CURRENT_DIR && bundle install --deployment --without ${BUNDLE_WITHOUT-development:test}
    popd
fi
