#!/bin/bash -e

# Copyright 2016 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/rc/config

# Install Essential Packages
apt-get update
apt-get install -y --no-install-recommends \
        nodejs \
        ruby \
        libgmp-dev \
        libgmp3-dev \
        zlib1g-dev \
        build-essential \
        libssl-dev \
        libreadline-dev \
        libyaml-dev \
        libsqlite3-dev \
        sqlite3 \
        libxml2-dev \
        libxslt1-dev \
        libcurl4-openssl-dev \
        libffi-dev

echo "export PATH=/home/application/ruby/bin:${PATH} GEM_PATH=/home/application/ruby GEM_HOME=/home/application/ruby BUNDLE_APP_CONFIG=/home/application/ruby/.bundle/config" | tee -a ${HOME}/.profile /etc/profile >/dev/null
