#!/bin/bash -el

# Copyright 2016 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/base/rc/config

if [ -f ${CURRENT_DIR}/requirements.txt ]; then
    sudo pip install -r ${CURRENT_DIR}/requirements.txt
fi
