#!/bin/bash -e

# Copyright 2016 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

APP_VENV=/home/application/.app_env

SOURCE_DIR=/var/lib/tsuru

source ${SOURCE_DIR}/base/rc/config

add_repository ppa:pypy/ppa
apt-get update
apt-get install pypy pypy-dev git -y
rm -f /usr/bin/python
ln -s /usr/bin/pypy /usr/bin/python
curl -sL https://raw.github.com/pypa/pip/master/contrib/get-pip.py | python

pip install virtualenv
virtualenv $APP_VENV
echo "export PATH=${APP_VENV}/bin:\${PATH}" | tee -a ${HOME}/.profile /etc/profile >/dev/null
echo "Defaults secure_path=\"${APP_VENV}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"" > /etc/sudoers.d/venv
chown -R ${USER}:${USER} ${APP_VENV}
