#!/bin/bash -e

# Copyright 2016 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/rc/config

add_repository ppa:pypy/ppa
apt-get update
apt-get install pypy pypy-dev git -y
rm -f /usr/bin/python
ln -s /usr/bin/pypy /usr/bin/python
curl -sL https://bootstrap.pypa.io/get-pip.py | pypy
