#!/bin/bash -e

# Copyright 2016 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/rc/config

apt-get update
apt-get install -y --no-install-recommends nginx

rm -rf /var/log/nginx /var/lib/nginx
mkdir -p /var/log/nginx /var/lib/nginx
chown -R ${USER}:${USER} /var/lib/nginx /var/log/nginx

cp ${SOURCE_DIR}/cordova/Procfile ${SOURCE_DIR}/default/Procfile
cp ${SOURCE_DIR}/cordova/etc/nginx.conf /etc/nginx/nginx.conf
