#!/bin/bash

# Copyright 2016 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/base/rc/config

echo "BUILDPACK: $BUILDPACK_URL"

cd $CURRENT_DIR
sudo /bin/sh -c "rm -rf /app && mkdir /app && cp -a . /app"
sudo -E ${SOURCE_DIR}/buildpack/build
sudo chown -R ${USER}:${USER} /app
echo "export PORT=8888" | tee /app/.profile.d/tsuru.sh >/dev/null
echo 'export PYTHONPATH=${PYTHONPATH}:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages' | tee -a /app/.profile.d/tsuru.sh >/dev/null

LC_ALL=C perl -lne '/^(.*?):/ && print "$1: /start $1"' /app/Procfile | sudo tee /Procfile >/dev/null
sudo sed -i "s^\(\s*\)\(.*\) | bash^\1exec /bin/bash -c \"\`\2\`\"^g" /start
sudo sed -i 's/chown -R .*//' /start
sudo sed -i 's/setuidgid .*/$(eval echo ${command})/' /start
