#!/bin/bash

# Copyright 2015 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru

if [[ -f ${SOURCE_DIR}/base/deploy ]]; then
    source ${SOURCE_DIR}/base/deploy
fi

if [[ -f ${SOURCE_DIR}/base/rc/config ]]; then
    source ${SOURCE_DIR}/base/rc/config
fi

echo "BUILDPACK: $BUILDPACK_URL"

cd $CURRENT_DIR
sudo /bin/sh -c "rm -rf /app && mkdir /app && cp -a . /app"
sudo -E ${SOURCE_DIR}/buildpack/build
sudo mkdir -p /app/.profile.d /home/heroku/.profile.d
echo "export PORT=\${PORT:-8888}" | sudo tee /app/.profile.d/tsuru.sh /home/heroku/.profile.d/tsuru.sh >/dev/null
echo 'export PYTHONPATH=${PYTHONPATH}:/usr/lib/python3/dist-packages:/usr/local/lib/python3/dist-packages' | sudo tee -a /app/.profile.d/tsuru.sh /home/heroku/.profile.d/tsuru.sh >/dev/null
sudo chown -R ${USER}:${USER} /app /home/heroku/.profile.d $CURRENT_DIR

LC_ALL=C perl -lne '/^(.*?):/ && print "$1: /start $1"' /app/Procfile | sudo tee /Procfile >/dev/null
