#!/bin/bash -e

# Copyright 2016 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru

${SOURCE_DIR}/base/install

cat >> /etc/profile <<EOF
export APP_WORKING_DIR=/app
export PROCFILE_PATH=/Procfile
EOF
