# Copyright 2017 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

FROM platform-{PLATFORM}
WORKDIR /tests
ADD . /tests
ADD common/* /tests/common
ADD https://github.com/sstephenson/bats/archive/master.tar.gz .
RUN mkdir ./bin && ./bats-master/install.sh .
RUN echo "echo 'ran base deploy'" > /var/lib/tsuru/base/deploy
RUN bin/bats common && bin/bats .
