# Copyright 2016 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

FROM platform-{PLATFORM}
WORKDIR /tests
ADD . /tests
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/sstephenson/bats.git && mkdir ./bin && bats/install.sh .
RUN echo "echo 'ran base deploy'" > /var/lib/tsuru/base/deploy
RUN echo "echo 'ran base config'" > /var/lib/tsuru/base/rc/config
RUN bin/bats .
