#!/bin/bash -el

# Copyright 2015 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

ERLANG_REPO=${ERLANG_REPO:-https://packages.erlang-solutions.com}

if [[ $ERLANG_VERSION ]] ; then
	ERLANG_TARGET="$ERLANG_REPO/erlang/debian/pool/esl-erlang_${ERLANG_VERSION}-1~ubuntu~xenial_amd64.deb"

	if ! (curl -fsS --retry 3 -L $ERLANG_TARGET -o /tmp/erlang.deb); then
		echo "ERROR: erlang version $ERLANG_VERSION is not supported."
		echo "You will find supported versions here: https://www.erlang-solutions.com/resources/download.html"
		exit 1
	fi

	echo "-- Installing erlang version: $ERLANG_VERSION --"
	if ! (sudo dpkg -i /tmp/erlang.deb); then
		echo "ERROR: There was a problem installing the erlang version"
		exit 1
	fi
	rm /tmp/erlang.deb
fi

if [[ $ELIXIR_VERSION ]] ; then
	echo "-- Using elixir version: $ELIXIR_VERSION --"
	ELIXIR_TARGET="$ERLANG_REPO/erlang/debian/pool/elixir_${ELIXIR_VERSION}-1~ubuntu~xenial_amd64.deb"

	if ! (curl -fsS --retry 3 -L $ELIXIR_TARGET -o /tmp/elixir.deb); then
		echo "ERROR: elixir version $ELIXIR_VERSION is not supported."
		echo "You will find supported versions here: https://www.erlang-solutions.com/resources/download.html"
		exit 1
	fi

	echo "-- Installing elixir version: $ELIXIR_VERSION --"
	if ! (sudo dpkg -i /tmp/elixir.deb); then
		echo "ERROR: There was a problem installing the elixir version"
		exit 1
	fi
	rm /tmp/elixir.deb
fi

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/base/rc/config

if [ -f ${CURRENT_DIR}/mix.exs ]; then
	pushd $CURRENT_DIR >/dev/null
	mix deps.get
	mix deps.compile
	popd >/dev/null
fi
