#!/bin/bash -el

# Copyright 2016 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/base/rc/config

if [ -f ${CURRENT_DIR}/mix.exs ]; then
	pushd $CURRENT_DIR >/dev/null
	yes | mix local.rebar --force
	yes | mix local.hex --force
	mix deps.get
	mix deps.compile
	popd >/dev/null
fi
