#!/bin/bash

# Copyright 2015 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
set -eu -o pipefail

curl -fsSL -o /tmp/erlang.deb https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
dpkg -i /tmp/erlang.deb
rm /tmp/erlang.deb

apt-get update
apt-get install -y --no-install-recommends esl-erlang elixir
