#!/bin/bash -el

# Copyright 2019 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/rc/config

apt-get update
apt-get install -y --no-install-recommends 

curl -R -O https://product-dist.ballerina.io/downloads/1.0.3/ballerina-linux-installer-x64-1.0.3.deb
dpkg -i ballerina-linux-installer-x64-1.0.3.deb
apt-get autoremove -y
rm -f ballerina-linux-installer-x64-1.0.3.deb