#!/bin/bash -e

# Copyright 2016 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/rc/config

apt-get update
apt-get install -y --no-install-recommends \
            openjdk-11-jdk \
            maven \
            tomcat9

cp $SOURCE_DIR/java/Procfile $SOURCE_DIR/default/Procfile

rm -rf /var/lib/tomcat9/webapps
ln -s ${CURRENT_DIR} /var/lib/tomcat9/webapps
mkdir -p /usr/share/tomcat9/common/classes /usr/share/tomcat9/server/classes /usr/share/tomcat9/shared/classes
chown -R ${USER}:${USER} /etc/tomcat9 /var/lib/tomcat9 /var/cache/tomcat9 /var/log/tomcat9 /usr/share/tomcat9
sed -i 's/8080/8888/' /etc/tomcat9/server.xml
