#!/bin/bash -e

# Copyright 2015 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source $SOURCE_DIR/base/rc/config

cp $SOURCE_DIR/java/Procfile $SOURCE_DIR/default/Procfile
echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
add_repository ppa:webupd8team/java
apt-get update
apt-get install -y --force-yes oracle-java8-installer
apt-get install -y --force-yes oracle-java7-installer
apt-get install -y --force-yes tomcat7 maven

rm -rf /var/lib/tomcat7/webapps
ln -s /home/application/current /var/lib/tomcat7/webapps
mkdir -p /usr/share/tomcat7/common/classes /usr/share/tomcat7/server/classes /usr/share/tomcat7/shared/classes
chown -R ${USER}:${USER} /etc/tomcat7 /var/lib/tomcat7 /var/cache/tomcat7 /var/log/tomcat7 /usr/share/tomcat7
sed -i 's/8080/8888/' /etc/tomcat7/server.xml
echo '#JAVA_HOME#' >> ${HOME}/.profile
