#!/bin/bash -e

# Copyright 2016 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

XMX=${JAVA_MAX_MEMORY-128}

mkdir -p /tmp/tomcat10-tomcat10-tmp
java -Djava.util.logging.config.file=/var/lib/tomcat10/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.awt.headless=true -Xmx${XMX}m -XX:+UseG1GC -classpath /usr/share/tomcat10/bin/bootstrap.jar:/usr/share/tomcat10/bin/tomcat-juli.jar -Dcatalina.base=/var/lib/tomcat10 -Dcatalina.home=/usr/share/tomcat10 -Djava.io.tmpdir=/tmp/tomcat10-tomcat10-tmp org.apache.catalina.startup.Bootstrap start
