#!/bin/bash

# Copyright 2016 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru

source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/base/rc/config

cd ${CURRENT_DIR}
dir /var/lib/activator --recursive
/var/lib/activator/activator stage
