#!/bin/bash

# Copyright 2015 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

ACTIVATOR_VERSION="1.3.2"

source /var/lib/tsuru/base/rc/config

apt-get update
apt-get install unzip -y

echo "Downloading activator..."

cd /tmp
curl -LO http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/typesafe-activator-${ACTIVATOR_VERSION}.zip
unzip typesafe-activator-${ACTIVATOR_VERSION}.zip
rm typesafe-activator-${ACTIVATOR_VERSION}.zip
mv activator-${ACTIVATOR_VERSION} /var/lib/activator
chown -R ${USER}:${USER} /var/lib/activator

echo "Installing openjdk 1.8.0..."
add_repository ppa:openjdk-r/ppa
apt-get update
apt-get install -y openjdk-8-jdk
