#!/bin/bash -el

# Copyright 2016 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/base/rc/config

APP_VENV=/home/application/.app_env

pushd $CURRENT_DIR
if [ -f ${CURRENT_DIR}/requirements.txt ]; then
    $APP_VENV/bin/pip install --no-cache-dir -r ${CURRENT_DIR}/requirements.txt
elif [ -f ${CURRENT_DIR}/setup.py ]; then
    $APP_VENV/bin/pip install --no-cache-dir -e ${CURRENT_DIR}/
fi
chown -R ${USER} ${CURRENT_DIR}
popd
