#!/bin/bash -el

# Copyright 2015 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/base/rc/config

pushd $CURRENT_DIR
if [ -f ${CURRENT_DIR}/requirements.txt ]; then
    sudo pip3 install -r ${CURRENT_DIR}/requirements.txt
elif [ -f ${CURRENT_DIR}/setup.py ]; then
    sudo pip3 install -e ${CURRENT_DIR}/
fi
chown -R ${USER} ${CURRENT_DIR}
popd
