#!/bin/bash -el

# Copyright 2015 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/base/rc/config

go_default_version="1.11.1"
if [ -z "${GO_VERSION}" ]; then
  GO_VERSION="${go_default_version}"
fi
echo "Installing Go ${GO_VERSION}..."
eval "$(gimme ${GO_VERSION})" >/dev/null 2>&1

if [ -z $(find ${APP_DIR}/current -name "*.go" -print -quit) ]; then
	exit 0
fi

APP_PATH=${APP_DIR}/src/current

if [ -n  "${GO_PKG_PATH}" ]
then
	APP_PATH=${APP_DIR}/src/${GO_PKG_PATH}
fi

mkdir -p ${APP_PATH}
rm -rf ${APP_PATH}
ln -s ${APP_DIR}/current ${APP_PATH}
chown ${USER}:${USER} ${APP_PATH}

pushd ${APP_PATH} >/dev/null 2>&1

# do not fail if the application is not go gettable
set +e
go get -d .
set -e

if [ -f ${APP_DIR}/.default_procfile ]
then
	echo "Procfile not found. Using default Procfile"

	echo "go build -o tsuru-app"
	go build -i -o tsuru-app
else
	go build -i
fi

popd >/dev/null 2>&1
