#!/bin/bash -el

# Copyright 2015 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/rc/config

apt-get update
apt-get install -y --no-install-recommends \
        bzr \
        mercurial \
        git \
        golang

cp ${SOURCE_DIR}/go/Procfile ${SOURCE_DIR}/default/Procfile
echo "GOPATH=${APP_DIR}" >> ${HOME}/.profile
echo 'PATH=$GOPATH:$GOPATH/bin:$PATH' >> ${HOME}/.profile
echo 'export PATH GOPATH' >> ${HOME}/.profile

export GOPATH="/go"
sudo mkdir -p $GOPATH
sudo chown ubuntu:ubuntu $GOPATH

GO_VERSIONS="1.11.12 1.12.7"

for GO_VERSION in ${GO_VERSIONS}; do
    echo "Installing Go ${GO_VERSION}..."
    sudo -u ubuntu -E go get "golang.org/dl/go${GO_VERSION}"
    sudo -u ubuntu -E $GOPATH/bin/go${GO_VERSION} download
done

sudo apt-get remove golang -y --autoremove --purge

for GO_VERSION in ${GO_VERSIONS}; do
    update-alternatives --install /usr/bin/go go $GOPATH/bin/go${GO_VERSION} 1
    update-alternatives --set go $GOPATH/bin/go${GO_VERSION}
done
