#!/bin/bash -el

# Copyright 2017 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/rc/config

apt-get update
apt-get install -y --no-install-recommends \
        bzr \
        mercurial \
        git

curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme -o /usr/bin/gimme
chmod +x /usr/bin/gimme

cp ${SOURCE_DIR}/go/Procfile ${SOURCE_DIR}/default/Procfile
echo "GOPATH=${APP_DIR}" >> ${HOME}/.profile
echo 'PATH=$GOPATH:$PATH' >> ${HOME}/.profile
echo 'export PATH GOPATH' >> ${HOME}/.profile
echo 'export GIMME_SILENT_ENV=1' >> ${HOME}/.profile
echo '[ -f ${HOME}/.gimme/envs/latest.env ] && source ${HOME}/.gimme/envs/latest.env' >> ${HOME}/.profile

sudo -u ubuntu mkdir -p ${HOME}/.gimme/versions
GO_VERSIONS="stable"
for GO_VERSION in ${GO_VERSIONS}
do
    echo "Installing Go ${GO_VERSION}..."
    sudo -u ubuntu gimme ${GO_VERSION}
done
