#!/bin/bash -el

# Copyright 2016 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru

source ${SOURCE_DIR}/base/rc/config
source ${SOURCE_DIR}/base/deploy

if test -e ${CURRENT_DIR}/nginx.conf; then
  sudo mv ${CURRENT_DIR}/nginx.conf /etc/nginx/nginx.conf || exit $?
fi

${SOURCE_DIR}/static/validate-nginx-conf /etc/nginx/nginx.conf
