#!/bin/bash -e

# Copyright 2015 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/rc/config

PY_VERSIONS="2.7.14 3.5.5 3.6.5 3.7.4 3.8.0 pypy2.7-5.10.0 pypy3.5-5.10.1"
PYENV_ROOT="/var/lib/pyenv"

export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get install -y --no-install-recommends \
    make build-essential libssl-dev zlib1g-dev libbz2-dev \
    libreadline-dev libsqlite3-dev curl llvm libncurses5-dev libncursesw5-dev \
    xz-utils tk-dev git libexpat1 libffi-dev

git clone https://github.com/pyenv/pyenv.git ${PYENV_ROOT}
git clone https://github.com/pyenv/pyenv-virtualenv.git ${PYENV_ROOT}/plugins/pyenv-virtualenv

# make pyenv available to platform deploys
echo "export PYENV_ROOT=$PYENV_ROOT" >> ${HOME}/.profile
echo "export PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH" | tee -a ${HOME}/.profile /etc/profile >/dev/null
echo 'eval "$(pyenv init -)"' | tee -a ${HOME}/.profile /etc/profile >/dev/null

# enable pyenv to pre install python versions
export PYENV_ROOT=$PYENV_ROOT
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)" # we only need pyenv at this point

export CFLAGS='-O2'

for pyversion in $PY_VERSIONS; do (pyenv install $pyversion); done

pyenv global 2.7.14

chown -R ${USER}:${USER} $PYENV_ROOT

apt-get remove --purge -y \
        libssl-dev zlib1g-dev libbz2-dev \
        libreadline-dev libsqlite3-dev llvm \
        libncurses5-dev libncursesw5-dev \
        tk-dev git libffi-dev

apt-get install -y --no-install-recommends \
        libssl1.0.0 zlib1g libbz2-1.0 \
        libsqlite3-0 libncurses5 \
        libncursesw5 libreadline7

apt-get autoremove --purge -y