#!/bin/bash -le

# Copyright 2015 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/base/rc/config

NODE_VERSION=stable

if [ -f ${CURRENT_DIR}/.node-version ]; then
    NODE_VERSION=$(cat ${CURRENT_DIR}/.node-version)
fi

export NVM_DIR=${HOME}/.nvm
[ ! -e ${NVM_DIR} ] && mkdir -p ${NVM_DIR}

. /etc/nvm/nvm.sh

nvm install ${NODE_VERSION}

rm -f ~/.nvm_bin
ln -s $NVM_BIN ~/.nvm_bin

KEEP_NODE_MODULES=$(test -f /tmp/app_envs && source /tmp/app_envs && echo $KEEP_NODE_MODULES)

if [ -d ${HOME}/.node_modules ] && [ -n "${KEEP_NODE_MODULES}" ]; then
	rm -rf ${CURRENT_DIR}/node_modules
	cp -R ${HOME}/.node_modules ${CURRENT_DIR}/node_modules
	rm -rf ${HOME}/.node_modules
fi

if [ -f ${CURRENT_DIR}/package.json ]; then
	pushd $CURRENT_DIR && npm install --production
	popd
	if [ -n "${KEEP_NODE_MODULES}" ]; then
		cp -R ${CURRENT_DIR}/node_modules ${HOME}/.node_modules
	fi
fi
