#!/bin/bash -le

# Copyright 2015 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
set -euf -o pipefail

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/rc/config

curl -fsSLo- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | sudo -E -u ${USER} bash

cat >> ~/.profile <<-EOF
export PATH=${PATH}:${HOME}/.nvm_bin
EOF
