#!/bin/bash -el

# Copyright 2015 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

echo "Deploying the PHP application..."

SOURCE_DIR=/var/lib/tsuru

source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/base/rc/config

# Deploying
echo "Starting application configuration"
sudo -E python ${SOURCE_DIR}/php/deploy.py install
python ${SOURCE_DIR}/php/deploy.py environment
