#!/bin/bash -e

# Copyright 2022 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
set -eu -o pipefail

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/rc/config
source ${SOURCE_DIR}/base/rc/os_dependencies

PHP_VERSIONS="5.6 7.0 7.1 7.2 8.0 8.1 8.2 8.3"

add_repository ppa:ondrej/php

packages=("nginx-core" "python3" "python3-yaml" "git" "apache2" "python-is-python3")
for version in $PHP_VERSIONS
do
    packages+=("php${version}" "php${version}-fpm" "libapache2-mod-php${version}")
done

export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get install -y --force-yes "${packages[@]}"

# Pinning composer on 2.2.x as composer 2.3+ dropped support for < PHP 7.2.5.
# See more: https://github.com/composer/composer/blob/main/CHANGELOG.md
COMPOSER_VERSION=2.2.12
curl -fsSL "https://getcomposer.org/download/${COMPOSER_VERSION}/composer.phar" -o /usr/local/bin/composer_phar
chmod +x /usr/local/bin/composer_phar
